(function () {
  var T = {
    en: {
      'side-sub':'User Manual',
      'back-link':'← Back to Setup Guides',
      'nav-g1':'Quick Start',
      'nav-prereq':'Prerequisites',
      'nav-step1':'Step 1 · LLM',
      'nav-step2':'Step 2 · Rerank',
      'nav-step3':'Step 3 · Embedding',
      'nav-step4':'Step 4 · Mem0',
      'nav-step5':'Step 5 · Onyx',
      'nav-step6':'Step 6 · Telegram Bot',
      'nav-step7':'Step 7 · Usage Example',
      'nav-g2':'Ops Reference',
      'nav-debug':'Debug Commands',
      'nav-services':'Service Management',
      'hdr-h1':'ABS AI User Manual',
      'hdr-p':'On-premise enterprise private AI solution — complete deployment & usage guide',
      'h2-prereq':'Prerequisites',
      'prereq-p':'All of the following services run under Ubuntu via WSL (Windows Subsystem for Linux).',
      'copy':'Copy',
      'copied':'Copied',
      'cmt-wsl':'# Open Windows Command Prompt, then enter WSL',
      'h2-step1':'Start the LLM Model',
      'h2-step2':'Start the Rerank Model',
      'h2-step3':'Start the Embedding Model',
      'h2-step4':'Start Mem0',
      'step4-title':'Mem0 Memory Layer',
      'h2-step5':'Start Onyx',
      'h2-step6':'Start & Configure the Telegram Bot',
      'step6-title':'Start the Service',
      'h2-step7':'Usage Example',
      'step5-title':'Enterprise Knowledge Base · Onyx',
      'step5-li1':'Start <strong>Docker Desktop</strong> on Windows',
      'step5-li2':'Start <strong>Onyx</strong>',
      'th-field':'Field',
      'th-value':'Value',
      'lbl-url':'Access URL',
      'lbl-email':'Admin Email',
      'lbl-pass':'Password',
      'step5-info':'Get API Key: go to <strong>Admin Panel</strong> &rarr; <strong>API Keys</strong> &rarr; click <strong>New</strong>',
      'h3-envvars':'Configure Environment Variables',
      'h3-telegram-params':'How to Get Telegram Configuration Parameters',
      'sc1-num':'Get TELEGRAM_BOT_TOKEN',
      'sc1-title':'Create a Bot via @BotFather',
      'tg1-li1':'Open Telegram and search for <strong>@BotFather</strong>',
      'tg1-li2':'Send <code>/newbot</code>',
      'tg1-li3':'Enter a bot name (e.g. <code>My AI Bot</code>)',
      'tg1-li4':'Enter a bot username — it must end in <code>bot</code> (e.g. <code>myai_bot</code>)',
      'tg1-li5':'BotFather replies with your <strong>Token</strong> — copy and save it',
      'sc2-num':'Get ALLOWED_USER_IDS',
      'sc2-title':'Get Your Numeric Telegram User ID',
      'tg2-li1':'Search for <strong>@userinfobot</strong>',
      'tg2-li2':'Send <code>/start</code>',
      'tg2-li3':'The bot replies with your numeric <strong>User ID</strong> — copy and save it',
      'step8-p':'Send a message to the bot in Telegram:',
      'chat-user':'ABS_AI four core components',
      'chat-bot':'According to ABS AI\'s documentation, its "four core components" are the four essential building blocks of the enterprise private AI solution — none of which can be left out. They are as follows:',
      'h3-core':'The Four Core Components',
      'core1-title':'1. Local LLM',
      'core1-desc':'Runs the Qwen 3.6 35B model on an NVIDIA RTX PRO 6000 Blackwell 96GB GPU. Uses a MoE architecture that activates only about 3B parameters during inference. All data stays local end-to-end — no third-party retention, no API bills.',
      'core2-title':'2. Onyx Enterprise Knowledge Base',
      'core2-desc':'Ingests company SOPs, product manuals, and internal documents into the system. The AI answers using "your own material" (via RAG), ensuring accuracy and relevance — ideal for onboarding, policy lookups, and finding answers fast.',
      'core3-title':'3. Mem0 Memory Layer',
      'core3-desc':'The AI remembers every conversation, user preference, and piece of project context. No need to re-explain background each time — it gets better the more the team uses it, delivering a personalized, coherent experience.',
      'core4-title':'4. Telegram Bot Interface',
      'core4-desc':'Interact with the AI through the familiar Telegram chat window. No new tools to learn — ask questions anytime, anywhere, including from mobile, lowering the barrier to use.',
      'h3-why':'Why Choose This Architecture?',
      'th-adv':'Advantage',
      'th-desc':'Description',
      'adv1':'Fully Compliant',
      'adv1-desc':'Sensitive data (MNPI, customer records, financial figures) never leaves the server room, meeting strict information-security requirements',
      'adv2':'Zero Marginal Cost',
      'adv2-desc':'One-time hardware investment, unlimited use afterward — no per-token billing',
      'adv3':'Ready Out of the Box',
      'adv3-desc':'Hardware, software, models, and configuration delivered as one integrated package, saving the engineering cost of building the stack yourself',
      'adv4':'Scalable',
      'adv4-desc':'A modular architecture leaves room to upgrade and grow with the team',
      'h2-debug':'Debug Commands',
      'h3-logs':'View Service Logs in Real Time',
      'lbl-portcheck':'Port Check',
      'h2-services':'Service Management Reference',
      'cmt-chmod':'# Ensure the startup script has execute permission',
    },
    zh: {
      'side-sub':'用户手册 · User Manual',
      'back-link':'← 返回安装指南',
      'nav-g1':'快速启动',
      'nav-prereq':'准备工作',
      'nav-step1':'第一步 · LLM',
      'nav-step2':'第二步 · Rerank',
      'nav-step3':'第三步 · Embedding',
      'nav-step4':'第四步 · Mem0',
      'nav-step5':'第五步 · Onyx',
      'nav-step6':'第六步 · Telegram Bot',
      'nav-step7':'第七步 · 使用示例',
      'nav-g2':'运维参考',
      'nav-debug':'调试命令',
      'nav-services':'服务管理',
      'hdr-h1':'ABS AI 用户手册',
      'hdr-p':'本地化企业私有 AI 解决方案 — 完整部署与使用指南',
      'h2-prereq':'准备工作',
      'prereq-p':'以下所有服务均通过 WSL（Windows Subsystem for Linux）在 Ubuntu 下执行。',
      'copy':'复制',
      'copied':'已复制',
      'cmt-wsl':'# 打开 Windows 命令提示符，进入 WSL',
      'h2-step1':'启动 LLM 模型',
      'h2-step2':'启动 Rerank 模型',
      'h2-step3':'启动 Embedding 模型',
      'h2-step4':'启动 Mem0',
      'step4-title':'Mem0 记忆层',
      'h2-step5':'启动 Onyx',
      'h2-step6':'启动并配置 Telegram Bot',
      'step6-title':'启动服务',
      'h2-step7':'使用示例',
      'step5-title':'企业知识库 · Onyx',
      'step5-li1':'在 Windows 中启动 <strong>Docker Desktop</strong>',
      'step5-li2':'启动 <strong>Onyx</strong>',
      'th-field':'字段',
      'th-value':'值',
      'lbl-url':'访问地址',
      'lbl-email':'管理员邮箱',
      'lbl-pass':'密码',
      'step5-info':'获取 API Key：进入 <strong>Admin Panel</strong> &rarr; <strong>API Keys</strong> &rarr; 点击 <strong>New</strong>',
      'h3-envvars':'配置环境变量',
      'h3-telegram-params':'如何获取 Telegram 配置参数',
      'sc1-num':'获取 TELEGRAM_BOT_TOKEN',
      'sc1-title':'通过 @BotFather 创建 Bot',
      'tg1-li1':'打开 Telegram，搜索 <strong>@BotFather</strong>',
      'tg1-li2':'发送 <code>/newbot</code>',
      'tg1-li3':'输入 Bot 名称（如 <code>My AI Bot</code>）',
      'tg1-li4':'输入 Bot 用户名，必须以 <code>bot</code> 结尾（如 <code>myai_bot</code>）',
      'tg1-li5':'BotFather 回复您的 <strong>Token</strong>，复制保存',
      'sc2-num':'获取 ALLOWED_USER_IDS',
      'sc2-title':'获取您的 Telegram 数字用户 ID',
      'tg2-li1':'搜索 <strong>@userinfobot</strong>',
      'tg2-li2':'发送 <code>/start</code>',
      'tg2-li3':'机器人将回复您的数字 <strong>User ID</strong>，复制保存',
      'step8-p':'在 Telegram 中向 Bot 发送消息：',
      'chat-user':'ABS_AI 四个核心',
      'chat-bot':'根据 ABS AI 的相关资料，其"四个核心"是指构建企业私有 AI 解决方案的四大关键组件，缺一不可。具体如下：',
      'h3-core':'四个核心组件',
      'core1-title':'1. 本地 LLM',
      'core1-desc':'运行 Qwen 3.6 35B 模型，部署在 NVIDIA RTX PRO 6000 Blackwell 96GB 显卡上。采用 MoE 架构，推理时仅激活约 3B 参数。所有数据全程本地，无第三方留存，无 API 账单。',
      'core2-title':'2. Onyx 企业知识库',
      'core2-desc':'将公司 SOP、产品手册、内部文件注入系统。AI 基于"你的资料"回答（RAG 技术），确保准确性和相关性，适用于新人上手、查规范、找答案。',
      'core3-title':'3. Mem0 记忆层',
      'core3-desc':'AI 记住每次对话、用户偏好及项目脉络。无需每次重新交代背景，AI 越用越懂团队，提供个性化且连贯的交互体验。',
      'core4-title':'4. Telegram Bot 接口',
      'core4-desc':'通过熟悉的 Telegram 聊天窗口与 AI 交互。无需学习新工具，支持随时随地（含移动端）发问，降低使用门槛。',
      'h3-why':'为什么选择这套架构？',
      'th-adv':'优势',
      'th-desc':'说明',
      'adv1':'合规无虞',
      'adv1-desc':'敏感数据（MNPI、客户资料、财务数字）不出机房，满足严格信息安全要求',
      'adv2':'零边际成本',
      'adv2-desc':'一次硬件投资，后续无限次使用，不按 Token 计费',
      'adv3':'开箱即用',
      'adv3-desc':'硬件、软件、模型、配置一体化交付，节省自建技术栈工程成本',
      'adv4':'可成长',
      'adv4-desc':'模块化架构预留升级空间，可随团队规模扩展',
      'h2-debug':'调试命令',
      'h3-logs':'实时查看服务日志',
      'lbl-portcheck':'端口检查',
      'h2-services':'服务管理参考',
      'cmt-chmod':'# 确保启动脚本有执行权限',
    }
  };

  window.GuideI18n.init(T);
})();
